version: '3.8'

services:
  cannabis-platform:
    container_name: cannabis-platform
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4002:3000"
    environment:
      - NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY=${NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY}
      - NEXT_PUBLIC_GOOGLE_CALENDAR_ID=${NEXT_PUBLIC_GOOGLE_CALENDAR_ID}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - ADMIN_USERS=${ADMIN_USERS}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - AUTH_URL=${AUTH_URL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      # Add other environment variables here if needed
      # Volumes are optional if you need persistence, but usually Next.js is stateless logic
      # volumes:
      #   - ./public/uploads:/app/public/uploads
