version: '3.8'

services:
  cannabis-platform:
    container_name: cannabis-platform
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # Ports removed, handled by Caddy
    environment:
      - NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY=${NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY}
      - NEXT_PUBLIC_GOOGLE_CALENDAR_ID=${NEXT_PUBLIC_GOOGLE_CALENDAR_ID}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - ADMIN_USERS=${ADMIN_USERS}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - AUTH_URL=${AUTH_URL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}

  caddy:
    image: caddy:2.7-alpine
    container_name: caddy-service
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - cannabis-platform

volumes:
  caddy_data:
  caddy_config:
