services:
  cannabis-platform:
    container_name: cannabis-platform
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:4002:3000" # Expose only locally, Nginx will proxy to this
    environment:
      - NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY=${NEXT_PUBLIC_GOOGLE_CALENDAR_API_KEY}
      - NEXT_PUBLIC_GOOGLE_CALENDAR_ID=${NEXT_PUBLIC_GOOGLE_CALENDAR_ID}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - ADMIN_USERS=${ADMIN_USERS}
      - ALLOWED_USERS=${ALLOWED_USERS}
      - AUTH_URL=${AUTH_URL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - NOTEBOOKLM_COOKIE=${NOTEBOOKLM_COOKIE}
